version: '3.1'

services:

  zookeeper-antispam:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper-antispam
    ports:
      - 2181:2181

  kafka-antispam:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka-antispam
    ports:
      - 9092:9092
    hostname: localhost
    links:
      - zookeeper-antispam
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-antispam:2181
      - KAFKA_CREATE_TOPICS=antispamMessages:1:1,antispamUserLogins:1:1,ipResultTopic:1:1,messagesResultTopic:1:1
    depends_on:
      - zookeeper-antispam

  kafka_manages_antispam:
    image: sheepkiller/kafka-manager:stable
    container_name: kafka_manages_antispam
    ports:
      - 9000:9000
    links:
      - zookeeper-antispam
      - kafka-antispam
    environment:
      - APPLICATION_SECRET=password
      - ZK_HOSTS=zookeeper:2181

  postgres-antispam:
    image: postgres:11
    container_name: postgres-antispam
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: antispam
      POSTGRES_USER: antispam
      POSTGRES_PASSWORD: antispam

  zoonavigator_web_antispam:
    image: elkozmon/zoonavigator-web:0.6.1
    container_name: zoonavigator_web_antispam
    ports:
      - 8001:8001
    environment:
      WEB_HTTP_PORT: 8001
      API_HOST: zoonavigator_api_antispam
      API_PORT: 9001
    depends_on:
      - zoonavigator_api_antispam

  zoonavigator_api_antispam:
    image: elkozmon/zoonavigator-api:0.6.1
    container_name: zoonavigator_api_antispam
    environment:
      API_HTTP_PORT: 9001
